name: yolov9
channels:
    - pytorch
    - nvidia
    - conda-forge
dependencies:
    - python=3.10
    - pip==24.3.1
    - pytorch==2.3.1
    - torchvision==0.18.1
    - pytorch-cuda=11.8
    -   pip:
            # Index URLs
            - --extra-index-url https://pypi.ngc.nvidia.com
            # Packages
            - -r requirements.txt